"""Short sidebar titles for sessions, generated by a bottom-tier model.

Topics are full instructions ("Bull case vs bear case: analyse IDFC first
bank stock"), so truncating them cuts exactly where the meaning starts.
A ~$0.00002 call turns them into something scannable ("IDFC First Bank").
"""
import re

from client import get_client

TITLE_MODEL = "google/gemini-2.5-flash-lite"

_SYSTEM = (
    "You title discussions. Given a discussion topic, reply with a title of "
    "at most 5 words that captures its subject. Reply with the title only — "
    "no quotes, no trailing punctuation, no 'Title:' prefix."
)


def _clean(raw: str) -> str:
    title = raw.strip().splitlines()[0] if raw.strip() else ""
    title = re.sub(r"^(?:title\s*:)\s*", "", title, flags=re.IGNORECASE)
    title = title.strip("\"'“”‘’ ").rstrip(".!")
    return title[:80]


def generate_title(topic: str) -> tuple[str | None, float]:
    """Returns (title, cost_usd); (None, 0) when generation fails or comes
    back empty — callers fall back to showing the topic."""
    try:
        client = get_client("openrouter")
        response = client.chat.completions.create(
            model=TITLE_MODEL,
            messages=[
                {"role": "system", "content": _SYSTEM},
                {"role": "user", "content": topic[:2000]},
            ],
            max_tokens=30,
        )
        cost = getattr(response.usage, "cost", 0) or 0
        title = _clean(response.choices[0].message.content or "")
        return (title or None), cost
    except Exception:
        return None, 0.0
