-- Sidebar titles, soft delete, and user feedback.

-- Short display title for the sidebar (auto-generated by a cheap model at
-- creation, user-renamable). The full topic stays the instruction agents see.
alter table mad_sessions add column if not exists title text;

-- Soft delete: hidden from every API surface, rows retained. Deleting also
-- clears share_id so any public link dies immediately.
alter table mad_sessions add column if not exists deleted_at timestamptz;

create table if not exists mad_feedback (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  category text,
  message text not null,
  page text,
  created_at timestamptz not null default now()
);

-- Backend uses the service role key, which bypasses RLS; enabling it with no
-- policies keeps anon/authenticated clients out entirely.
alter table mad_feedback enable row level security;
